dependencies:
  # Platform components
  - name: astronomer
    condition: global.astronomerEnabled
    tags:
      - platform
  - name: nginx
    condition: global.nginxEnabled
    tags:
      - platform

  # Monitoring stack
  - name: grafana
    condition: global.grafanaEnabled
    tags:
      - monitoring
  - name: prometheus
    condition: global.prometheusEnabled
    tags:
      - monitoring
  - name: alertmanager
    condition: global.alertmanagerEnabled
    tags:
      - monitoring
  - name: kube-state
    condition: global.kubeStateEnabled
    tags:
      - monitoring

  # Logging stack
  - name: elasticsearch
    condition: global.elasticsearchEnabled
    tags:
      - logging
  - name: kibana
    condition: global.kibanaEnabled
    tags:
      - logging
  - name: fluentd
    condition: global.fluentdEnabled
    tags:
      - logging

  # Airflow chart is deployed by the platform
  - name: airflow
    condition: global.airflowEnabled

  # Istio
  - name: istio-init
    repository: "https://storage.googleapis.com/istio-release/releases/1.1.7/charts/"
    condition: global.istioEnabled
    tags:
      - istio

  - name: istio
    repository: "https://storage.googleapis.com/istio-release/releases/1.1.7/charts/"
    condition: global.istioEnabled
    tags:
      - istio
