version: 2

jobs:
  platform:
    machine:
      image: ubuntu-1604
      resource_class: large
    steps:
      - checkout
      - run:
          name: Platform
          command: bin/run-ci platform
  monitoring:
    machine:
      image: ubuntu-1604
      resource_class: large
    steps:
      - checkout
      - run:
          name: Monitoring
          command: bin/run-ci monitoring
  logging:
    machine:
      image: ubuntu-1604
      resource_class: large
    steps:
      - checkout
      - run:
          name: Logging
          command: bin/run-ci logging
  kubed:
    machine:
      image: ubuntu-1604
    steps:
      - checkout
      - run:
          name: Kubed
          command: bin/run-ci kubed

workflows:
  version: 2
  install-helm-tags:
    jobs:
      - platform
      - monitoring
      - logging
      - kubed
