version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      # - run:
      # -   name: Lint
      # -   command: make lint
      - run:
          name: Dry Run
          command: bin/run-ci
