################################
## Astronomer Registry ConfigMap
#################################
{{ if .Values.global.baseDomain }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-registry
  labels:
    component: registry
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
data:
  config.yml: |-
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    http:
      addr: :5000
      # debug:
      #   addr: :5001
      #   prometheus:
      #     enabled: true
      #     path: /metrics
      headers:
        X-Content-Type-Options: [nosniff]
    auth:
      token:
        realm: "https://houston.{{ .Values.global.baseDomain }}/v1/registry/authorization"
        service: {{ .Values.registry.auth.service | quote }}
        issuer: {{ .Values.registry.auth.issuer | quote }}
        rootcertbundle: /etc/docker/ssl/tls.crt
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    notifications:
      endpoints:
        - name: "houston"
          url: "http://{{ .Release.Name }}-houston:{{ .Values.ports.houstonHTTP }}/v1/registry/events"
          timeout: 3s
          threshold: 10
          backoff: 1s
          ignoredmediatypes:
            - application/octet-stream
{{- end }}
