# Default values for astronomer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Images for Astronomer
images:
  commander:
    repository: astronomerinc/ap-commander
    tag: 0.9.1-alpha.3
    pullPolicy: IfNotPresent
  registry:
    repository: astronomerinc/ap-registry
    tag: 0.9.1-alpha.3
    pullPolicy: IfNotPresent
  houston:
    repository: astronomerinc/ap-houston-api
    tag: 0.9.1-alpha.3
    pullPolicy: IfNotPresent
  orbit:
    repository: astronomerinc/ap-orbit-ui
    tag: 0.9.1-alpha.3
    pullPolicy: IfNotPresent
  dbBootstrapper:
    repository: astronomerinc/ap-db-bootstrapper
    tag: 0.9.1-alpha.3
    pullPolicy: IfNotPresent
  cliInstall:
    repository: astronomerinc/ap-cli-install
    tag: 0.9.1-alpha.3
    pullPolicy: IfNotPresent
  prisma:
    repository: astronomerinc/ap-prisma
    tag: 0.9.1-alpha.3
    pullPolicy: IfNotPresent
  kubeReplicator:
    repository: astronomerinc/ap-kube-replicator
    tag: 0.9.1-alpha.3
    pullPolicy: IfNotPresent

orbit:
  env: {}
  resources: {}
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi

houston:
  # Houston datastore
  backendSecretName: ~
  backendConnection: {}
    # user: ~
    # pass: ~
    # host: ~
    # port: ~
    # db: ~
  # Airflow backends
  airflowBackendSecretName: ~
  airflowBackendConnection: {}
    # user: ~
    # pass: ~
    # host: ~
    # port: ~
    # db: ~

  # This specifies an optional secret name to use to sign JWTs.
  # If not specified, we use an auto-generated, self-signed certificate.
  jwtSigningCertificateSecretName: ~

  env: {}
  resources: {}
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi

  # Any Houston configuration. Reference here:
  # https://github.com/astronomer/houston-api/blob/master/config/default.yaml
  config: {}

prisma:
  env: {}
  resources: {}
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi


commander:
  env: {}
  resources: {}
   # limits:
   #  cpu: 100m
   #  memory: 128Mi
   # requests:
   #  cpu: 100m
   #  memory: 128Mi

registry:
  resources: {}
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi

  persistence:
    # Enable persistent storage
    enabled: true
    # Size of volume to provision
    size: 100Gi
    # If using a custom storageClass, pass name ref to all statefulSets here
    storageClassName: ~

  auth:
    secretName: ~
    connection: ~
    service: "docker-registry"
    issuer: "houston"

  gcs:
    enabled: false
    bucket: ~
    keyfile: /var/gcs-keyfile/astronomer-gcs-keyfile
    rootdirectory: /
    chunksize: '5242880'

install:
  resources: {}
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi

kubeReplicator:
  resources: {}
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi


ports:
  houstonHTTP: 8871
  commanderHTTP: 8880
  commanderGRPC: 50051
  orbitHTTP: 8080
  registryHTTP: 5000
  registryScrape: 5001
  installHTTP: 80
  prismaHTTP: 4466
